services:

  scribe_api:
    container_name: scribe_api
    build:
      context: api
      dockerfile: Dockerfile.prod
      target: build
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - scribe_api
      - scribe_postgres
    env_file:
      - ./db-variables-dev.env
    depends_on:
      - scribe_postgres

  scribe_postgres:
    container_name: scribe_postgres
    image: postgres:15.8-alpine3.20
    restart: unless-stopped
    user: postgres
    networks:
      - scribe_postgres
    volumes:
      - scribe_postgres_data:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d/
    env_file:
      - ./db-variables-dev.env

volumes:
  scribe_postgres_data:

networks:
  scribe_api:
    driver: bridge
  scribe_postgres:
    driver: bridge
