version: "3.9"

services:

  nginx_scribe_api:
    container_name: nginx_scribe_api
    build:
      context: ./nginx
      args:
        - DEPLOY_ENV=PROD
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - scribe_api
    depends_on:
      - scribe_api
    volumes:
      - scribe_nginx_logging:/vol/log/nginx

  scribe_api:
    container_name: scribe_api
    build:
      context: api
      dockerfile: Dockerfile.prod
      target: deploy
    environment:
      - ADDR=0.0.0.0
      - PORT=8080
      - GO_ENV=production
      - GIN_MODE=release
    restart: unless-stopped
    env_file:
      - ./db-variables.prod.env
    depends_on:
      - scribe_postgres
    command: ./run

  scribe_postgres:
    container_name: scribe_postgres
    image: postgres:15.8-alpine3.20
    restart: unless-stopped
    user: postgres
    networks:
      - scribe_postgres
    volumes:
      - scribe_postgres_data:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d/
    env_file:
      - ./db-variables-dev.env

volumes:
  scribe_nginx_logging:
  scribe_postgres_data:

networks:
  scribe_api:
    driver: bridge
  scribe_postgres:
    driver: bridge
