services:

  scribe_api:
    container_name: scribe_api
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "8000:8000"
      - "40000:40000"
    networks:
      - scribe_api
      - scribe_postgres
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
    volumes:
      - ./api:/go/src/api
    env_file:
      - ./db-variables-dev.env
    depends_on:
      - scribe_postgres

  scribe_postgres:
    container_name: scribe_postgres
    image: postgres:15.8-alpine3.20
    restart: unless-stopped
    user: postgres
    ports:
      - "5432:5432"
    networks:
      - scribe_postgres
    volumes:
      - scribe_postgres_data:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d/
    env_file:
      - ./db-variables-dev.env


volumes:
  scribe_postgres_data:
  scribe_api:


networks:
  scribe_api:
    driver: bridge
  scribe_postgres:
    driver: bridge
