FROM  golang:1.23.4-alpine3.21

LABEL maintainer="Realize Security Ltd."

WORKDIR /go/src/api

ENV GO111MODULE=on
ENV GIN_MODE=debug
ENV GO_ENV=development
ENV DEPLOYMENT=development
ENV REFRESH_SECRET=secret-token-value
ENV CGO_ENABLED=0

COPY go.mod .
COPY go.sum .

RUN go mod download

# create a new executing directory '/go/src/exec_dir' and move the binary there
# avoids trying to drop the binary into the volume created for live reload
# home directory is added to get round build cache exceptions
RUN apk add --no-cache bash && \
    apk add --no-cache ca-certificates && \
    adduser --disabled-password scribe && \
    apk update && apk add --no-cache git && \
    apk add inotify-tools && \
    mkdir -p /vol/log && \
    mkdir /go/src/exec_dir && \
    chown -R scribe:scribe /go/src/exec_dir && \
    chown -R scribe:scribe /vol/log

RUN go install github.com/go-delve/delve/cmd/dlv@v1.23.0
RUN chown scribe:scribe /go/bin/dlv

COPY . .

USER scribe:scribe
RUN PATH=$PATH:/usr/bin

ENTRYPOINT sh golang_hot_reload.sh